### ISSUE TITLE
About relationship between similarity function and EMD distance

### ISSUE THREAD

**Issue by lvXiangwei** [ZhuYun97/RoSA#3]
https://github.com/ZhuYun97/RoSA/blob/04a9275094972d49829fb712a6e60d13652d3b3f/model.py#L102

In RoSA paper, I notice that you use $s(x, y) = 1 - EMD(x, y)$. Should it be `S = 1 - torch.mul(transport_matrix, cost_matrix).sum(dim=1).sum(dim=1, keepdim=True) # 2S - 1 ` in the code? I don't know if I understand it completely. By the way, what does the comment `"2S - 1"` mean?

**Comment by ZhuYun97** [comment]
In this repo, we use $s(\mathbf{x},\mathbf{y})=\langle \tilde{\mathbf{\Gamma}}, 1-\mathbf{D}\rangle_\mathrm{F}$. But `S = torch.mul(transport_matrix, 1-cost_matrix).sum(dim=1).sum(dim=1, keepdim=True)`  (i.e., $S=\langle \tilde{\mathbf{\Gamma}}, 1-\mathbf{D}\rangle_\mathrm{F}$) or `S = 1 - torch.mul(transport_matrix, cost_matrix).sum(dim=1).sum(dim=1, keepdim=True)` (i.e., $S=1-\langle \tilde{\mathbf{\Gamma}}, \mathbf{D}\rangle_\mathrm{F}$) both work, because the partial gradients  $\frac{\partial S}{{\partial \mathbf{D}}}$ are the same (the transportation matrix can be considered as constant). For consistent usage, I have already updated the calculation of the similarity function (using 1-emd).
For the annotation, you can neglect it.

**Comment by lvXiangwei** [comment]
I see. Thanks for your answer.
