### ISSUE TITLE
关于损失函数中正样本间EMD距离的计算

### ISSUE THREAD

**Issue by yufeng1027** [ZhuYun97/RoSA#4]
Excuse me ,In RoSA/model.py 128 line
            loss_pos = self._batched_semi_emd_loss(out1, avg_out1, out2, avg_out2, rescale_ratio=rescale_ratio) * 2
Why to multiply by 2 after calculating the EMD distance between positive samples，Thank you for your reply。

**Comment by ZhuYun97** [comment]
The positive pair will be influenced by topology information which is computed as [rescale_ratio](https://github.com/ZhuYun97/RoSA/blob/ea2e9f37e6458265f63f0aa4645a309e54746ade/model.py#L126). The values in rescale_ratio belong to [0.5, 1]. In order to restore the impact of positive pairs, we empirically set 2 here.
